### ISSUE TITLE
SPIKE: Investigate possible regression in hApp installation time in develop

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3449] opened 2024-03-15 09:50 UTC
Note: This is a timeboxed spike!

1. Collect Data:
  1.1. Installation time for branch `develop` DEBUG build
  1.2. Installation time for branch `develop` RELEASE build
  1.3. Installation time for a known good tag DEBUG build
  1.4. Installation time for a known good tag RELEASE build
2. Evaluation pause. If the release builds are tolerable, this effort should cease and a lower-priority task to either speed up debug builds or have CI/dev environments use release built cratelift should be created.
3. If the release builds are NOT tolerable, proceed with timeboxed investigative debugging and report on the results.

**Comment by ThetaSinner** [comment] 2024-04-04 15:14
Anecdotal information from me that my sweettests (happ I'm working on) are spending a very long time on app installs. Like 30s where the rest of the test takes <5s.

**Comment by ThetaSinner** [comment] 2024-04-04 15:16
Refinement notes:
- Treat this as a timeboxed task initially to work out how serious the regression is. If it's serious then we can work out what to do with it.
- Check the Rust client tests to see how long app installs are taking with a simple wasm.

**Comment by neonphog** [comment] 2024-04-10 16:11
Moving the original Issue description into a comment so I can summarize in the description

---

hApp installation using Holochain v0.3 takes longer than v0.2 on both the Rust and JS client. App installations are slower under Holochain 0.3 by a factor of ~ 1.4

Measurements using the JS client while creating a new conductor and installing mewsfeed 10 times in a row:

Holochain 0.2.6

installation took 2523.9288330000004 ms
installation took 298.4932910000007 ms
installation took 289.320917 ms
installation took 291.08895799999937 ms
installation took 291.3211250000004 ms
installation took 284.6481670000003 ms
installation took 299.33437499999945 ms
installation took 289.42320799999925 ms
installation took 282.82445800000005 ms
installation took 286.25887499999953 ms

mean: 513.6642206999999 ms
median: 291.08895799999937 ms

Holochain 0.3.0-dev.39

installation took 5490.287084 ms
installation took 393.8590830000012 ms
installation took 396.8575000000001 ms
installation took 394.1591669999998 ms
installation took 399.62508399999933 ms
installation took 396.0837909999991 ms
installation took 395.3886249999996 ms
installation took 396.6821250000012 ms
installation took 396.3104170000006 ms
installation took 397.9891659999994 ms

mean: 905.7242042 ms
median: 396.6821250000012 ms

https://chat.holochain.org/holo/pl/95cqqircp3f5f8fd3aredgjnue

**Comment by jost-s** [comment] 2024-05-16 11:37
@maackle Can we close this based on your work?

**Comment by maackle** [comment] 2024-05-20 21:38
Yeah I think it's safe to close. We know that wasm compilation is what's taking the most time, and we don't have much control over that.

**Comment by zippy** [comment] 2024-10-22 15:35
looks like this is complete, only related to debug builds.  Wind-tunnel has scenarios for revealing time.

**Closed by zippy** 2024-10-22 15:35 UTC
Labels: Spike, triage
