### ISSUE TITLE
Unable to install large apps

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#966] opened 2021-09-08 10:34 UTC
The hard 16MB limit on websocket payload sizes has become a blocking error for me. The output from Tryorama in my tests looks like this (stack frames truncated):

```
20:16:58 [tryorama: player c0] debug: initialized
20:16:58 [tryorama: player c0] debug: Player.installHapps
20:16:58 [tryorama: player c0] debug: Player.adminWs()
20:16:58 [tryorama: player c0] debug: Player.installHapp(["/home/pospi/projects/holo-rea/valueflows-project-metarepo/holo-rea/happs/observation/hrea_observation.dna","/home/pospi/projects/holo-rea/valueflows-project-metarepo/holo-rea/happs/planning/hrea_planning.dna"], noAgentPubKey)
20:17:13 [tryorama] error: Test error: 'Error: Timed out in 15000ms: register_dna\n'
```

I have [recently](https://github.com/holo-rea/holo-rea/commit/1242b01383dc9757367853957a6867038f3ef6c5) added a `wasm-opt` pass to my build to see if it alleviates the issue, but unfortunately the byte savings are modest (~25% shaved off).

Suggest this be elevated as a serious issue as more complex applications continue to be developed. While my [dna configs](https://github.com/holo-rea/holo-rea/blob/cb04e68/happs/observation/dna.yaml) may appear to list a large number of zomes, I expect this will be nothing compared to highly modular app architectures being envisioned by https://neighbourhoods.network/ and https://ad4m.dev/. It is worth noting that the tests failing currently only involve 2 DNAs containing 19 zomes- the full hREA suite will be in excess of 15 DNAs and will also require several [supporting auxilliary zomes](https://github.com/holo-rea/ecosystem/wiki/Modules-in-the-HoloREA-framework#dependent-module-breakdown) in almost any useful configuration. And this does not factor in UI apps spanning multiple collaboration spaces, which may require access to *multiple module suites* simultaneously- leading to multipliers of 15-20 odd interrelated DNAs all being part of the same hApp bundle.

To those pondering whether I might be able to reduce the filesize of things in other ways, I don't see this as a solution or even a long-term deferral of the problem.

I suspect the issue will have to be solved mostly on the `hc-utils` side with the support of another API method or two from core, basically to chunk larger input files and send in pieces before reassembling on the other side.

**Comment by pospi** [comment] 2021-12-23 07:33
As of Holochain `.121` and HDK `.117`, this is being neatly caught in a helpful error message which indicates the size of the failed payload-

```Dec 23 17:32:26.429 ERROR holochain_websocket::websocket: websocket_error_from_network=Capacity("Message length too big: 27873497 > 16777216")
Error: Failed to receive response to request```

**Comment by maackle** [comment] 2022-01-18 23:20
@pospi this may be relevant: https://github.com/holochain/holochain/blob/90c0bff842623950336908f36a9cbf3363b86b8f/crates/holochain_types/src/app.rs#L87-L135

I'm not sure what tryorama is doing these days, but Holochain does allow you to either pass the serialized bytes of an AppBundle over the websocket, *or* specify a local path from which to read the bundle. The latter option should avoid the need to send the entire wasm over websocket.

Tryorama may need to be updated to use this other way of specifying the app bundle. It comes down to using `{"path": PATH, ...}` instead of `{"bundle": BUNDLE}` in the payload.

**Comment by jost-s** [comment] 2022-01-21 19:45
@maackle If I'm not mistaken, @pospi tried to use the `path` instead of the `bundle` as he states in the [comment above](https://github.com/holochain/holochain/issues/966#issuecomment-949304448), which resulted in a timeout nevertheless.

Does this look like a Tryorama issue to you anyway?

**Comment by maackle** [comment] 2022-01-21 22:58
Actually this is a different place: @artbrock was referring to the app manifest itself, where you can choose "bundled" vs "path" for each bundled DNA, but in my most recent comment I am referring to payload of the `InstallAppBundle` interface method, which specifies how to fetch *the entire bundle itself*. That would bypass the 16MB limit without relying on relative paths.

The timeout @pospi is experiencing may or may not be related, though.

**Comment by pospi** [comment] 2022-01-31 01:43
Sure, the project is here- https://github.com/holo-rea/holo-rea/
Build takes a while, but the setup is pretty standard. See `bundles/full_suite/hrea_suite.happ` after `pnpm i && npm run build` completes- size is around 22MB. If you need PNPM first- `npm i -g pnpm`.

**Comment by jost-s** [comment] 2022-02-01 15:24
@pospi Thanks for the instructions. I've built the hApp.
The problem is simply a default timeout in the `@holochain/client` that's hit before finishing the hApp installation. Once increased, the hApp installs successfully.

We need to include a setting for this timeout from Tryorama.

To unblock you now, you can set `node_modules/@holochain/client/lib/websocket/common.js#DEFAULT_TIMEOUT` in your project to a higher value like `50000`.

**Comment by pospi** [comment] 2022-02-07 03:05
This does seem to work, at least for the tests I have with 3 DNAs which total >16MB when all combined. **However**, each individual module is <16MB and it is possible that `@holochain/client` might still hang if a single DNA bundle exceeds this size.

If desirable I can recompose these modules into a "DNA monolith" kind of pattern so that we can test with individual `*.dna` files in excess of 16MB. I think it best to leave this issue open until all possible size thresholds have been tested.

**Comment by Connoropolous** [comment] 2022-02-20 00:39
I have a solution for at least a "released" version of holo-rea, along with release automation, which uses the `url` style bundle handling, since given the assets are uploaded to the release, they are available online for download and installation 
https://github.com/holo-rea/holo-rea/pull/193

It also basically handles your concerns @pospi regarding "I would need to figure out some way of substituting environment variables into DNA manifest files at install time to make it workable."

**Comment by pospi** [comment] 2022-02-21 06:12
This is great and resolves the issue for now.

To reiterate for clarity- I suspect this is only working due to the size of each individual referenced URL being <16MB. It would be worth testing with a bundle that has an *individual* DNA exceeding this size before closing the issue.

**Comment by Connoropolous** [comment] 2022-02-22 02:45
@pospi 
Looks like even in `dna.yaml` and packed `Dna`s, they use the `Location` struct and resolver. 
What this might mean in practice is that they may wish to never increase the 16mb websocket message size limit. Instead, a solution to the "individual DNA exceeding this size limit" issue, is that you could do the exact same thing, and specify your Zome wasm sources, as `path` or `url`, depending on either a local resource, or an online resource, to fetch and install. This should mean that packed Dna and Happ files should always be able to be converted to being very small, by not using the 'bundled' variant of the `Location` enums to specify the resources.

Since the WASMS are ultimately the ones most likely to bloat in size, this would be a key step to being able to handle these.

From the view I'm currently looking at it from, this is a pretty sturdy solution we have available to us, I am not sure there's much better that `holochain` could offer up.

https://github.com/holochain/holochain/blob/ba04d446630cb48a10c494bb1d71e80c866af5d4/crates/holochain_types/src/dna/dna_manifest/dna_manifest_v1.rs#L41

**Comment by Connoropolous** [comment] 2022-02-22 02:50
The open timeout issue over in tryorama could stay open https://github.com/holochain/tryorama/issues/106
while this one gets closed?

**Comment by maackle** [comment] 2022-02-23 18:04
I'm glad you've found a solution. Before we close this issue altogether, I wanted to see if [my previous comment](https://github.com/holochain/holochain/issues/966#issuecomment-1018925014) was applicable at all. I was saying that you can use bundled locators for both DNAs and zomes within those DNAs, even if any item is over 16MB, because in the actual admin interface command `InstallAppBundle`, you don't have to send the entire bundle over websocket, but rather you can just specify a path to where it exists on the local filesystem. Then there is no need to add that indirection directly in your manifest files.

**Comment by pospi** [comment] 2022-03-26 09:04
@maackle I've implemented a workaround now... can't say I find it terribly clean, but it works. Would be interested in your opinions in the additional complexity added to [hREA's build script](https://github.com/holo-rea/holo-rea/blob/0.0.1-alpha.5/scripts/package-dnas.sh).

Basically, we have to:

- determine the root path of the repo for substitution purposes (expected)
- templatise all DNA and app bundles (also expected)
- have a flag to control whether to use `path` or `bundle` refs in the DNA bundle, which I'm pretty certain must be turned on for a release and off for local development otherwise those downloading a release package would be unable to locate the locally-referenced zome WASMs
- have a flag to control whether to use `path` or `url` refs in the app bundle

The two are therefore interrelated, and depending on whether you are aiming for a local webhapp or a deployable one you have to have a totally different configuration all the way from step 1 in a 3-step build process. Seems like a lot of moving parts&mdash; wish things were simpler, but happy to consider this resolved for my purposes for now.

Perhaps if anybody ends up with a *single DNA* in excess of 16MB, this issue could be opened again as I still suspect that would cause installation failures.

**Comment by maackle** [comment] 2022-03-28 16:50
@pospi I'm wondering how much of the complexity you describe is essential, and how much is a result of the particulars of your project's setup. For instance, I wouldn't expect you to need to templatize manifests if you simply had two different manifests, one for development and one for release builds, which I think is a common pattern in other app frameworks I've used. Would this be a viable option?

As someone who is not building and maintaining a large hApp like yourself, could you make a case for why you are doing things the way you are, and perhaps make a suggestion for how you could see Holochain's interface structured differently to make it easier for all devs?

> have a flag to control whether to use `path` or `url` refs in the app bundle

I'm also not sure why you didn't mention using `bundle` refs in the app manifest. My previous comment was suggesting that you could indeed do this, if you specify a local file path when *installing* the bundle, rather than sending the entire bundle payload over websocket. I am still wondering if my previous comment was helpful, and if not, why not. You mentioned that this is a workaround, but I'm not sure what limitation you are currently working around.

**Comment by Connoropolous** [comment] 2022-03-29 16:17
Ive been working with pospi a bit around this one, and the only part ill comment on is this bit: 
> For instance, I wouldn't expect you to need to templatize manifests if you simply had two different manifests, one for development and one for release builds, which I think is a common pattern in other app frameworks I've used. Would this be a viable option?

I think it may be common in the future for these to be templates and have values injected because when you are doing development and using 'path' it needs to be an absolute not relative path which makes it different on each computer. In production, if using 'url' it also needs to be dynamic because the url includes the specific release version for that release.

I am personally getting the sense all is well and these options are plenty!

**Comment by Connoropolous** [comment] 2022-03-29 16:20
I propose to close the issue and as Pospi says if something related arises this cam be reopened or just a more focused issue crested and reference this one.

**Closed** 2022-03-29 16:20 UTC

**Comment by Connoropolous** [comment] 2022-03-29 18:43
I see. Well, for example, we want our .webhapp for holo-rea to be installed via the launcher. Whether it works or not will be contingent on what method of installAppBundle the Launcher uses, because like tryorama (except from rust code instead of Js) it installs the happ via websockets. I will look into it and report back.

**Comment by Connoropolous** [comment] 2022-03-29 18:47
Right, so installAppBundle in the launcher uses Bundled variant which means that you can hit the websocket msg too large issue. 

https://github.com/holochain/launcher/blob/2ca0edc6c24023ec9209c3dac44d115816a4500b/src-tauri/src/commands/install_app.rs#L98

If this were fixed in Launcher, we could perhaps switch back to not using Url. 

@guillemcordoba

**Comment by Connoropolous** [comment] 2022-03-29 21:23
Created this other issue to track that: https://github.com/holochain/launcher/issues/46

**Comment by pospi** [comment] 2022-04-03 07:47
@jost-s 

>  if you simply had two different manifests

I see this as an anti-pattern; and a violation of [dev/prod parity](https://12factor.net/dev-prod-parity). You want the two to be as close as possible to avoid unnecessary human error.

As to `bundled`- as @Connoropolous said, it breaks installation via Holochain Launcher due to the overall hApp bundle size and so `url` was the only viable option for production. I hope eventually there will be some `devhub` option that can reference an `EntryHash` stored in that Holochain DNA, so that we don't have to rely on Web2 services for deployment.

Also to note that `bundled` breaks the Holochain Sandbox for the same reasons, which is why `path` has to be used in that case.

**Comment by maackle** [comment] 2022-04-04 16:50
Thanks @Connoropolous, yes, the context that I was missing here was that you are installing via the Launcher. So, I agree that the Launcher should be modified to use `path` instead of `bundled`. I hope that your issue gets picked up.

@pospi, that makes sense, and perhaps your manifest is already quite large and complex, so I can see why you would want to minimize chances for structural mismatches between the two.

Do you think something like a "dev manifest override" would help? There could be an option to provide a partial manifest which overrides parts of the production manifest. Parts not specified in the override would be pulled from the prod manifest, and parts specified in the override which don't have a counterpart in the prod manifest would result in an error.

**Comment by Connoropolous** [comment] 2022-04-04 18:21
Opened a PR for that

**Comment by pospi** [comment] 2022-04-05 03:01
> Do you think something like a "dev manifest override" would help?

That sounds sensible at face value- Docker Compose does it this way. However, the merging behaviour of YAML files might make the final result less than ergonomic since it's a property that needs to change and not a value... I guess you'd have to override the production `bundled` value as `~` and inject a `path` value? But this also does not resolve the need to inject a dynamic value for `path` to achieve portability between different dev environments.
