### ISSUE TITLE
Broken compilation with `rustc 1.55` 

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#977] opened 2021-09-14 11:49 UTC
To reproduce:

```bash
rustup toolchain install 1.55
rustup default 1.55-x86_64-unknown-linux-gnu
cargo install holochain
```

The last command gives this error:

```
    Updating crates.io index
  Installing holochain v0.0.104
error: failed to compile `holochain v0.0.104`, intermediate artifacts can be found at `/tmp/cargo-installVlsnPI`

Caused by:
  failed to download `bit-set v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/bit-set-0.2.0/Cargo.toml`

Caused by:
  dependency (bit-vec) specified without providing a local path, Git repository, or version to use.
```

The temporary workaround is to downgrade rust to 1.54 with:

```bash
rustup toolchain install 1.54
rustup default 1.54
```

Now holochain compiles again with no issues.

**Comment by freesig** [comment] 2021-09-15 04:17
@timotree3 Did you have a work around for this? I thought I saw you mention it.

**Comment by timotree3** [comment] 2021-09-15 13:14
The work around that worked for me 3 weeks ago was to fork `bit-set`, fix its `Cargo.toml`, and add a `Cargo.toml` patch that points to my fork. 

Here is what you can try adding holochain's `Cargo.toml` (or your `Cargo.toml` if you depend on holochain)

```
[patch.crates-io]
bit-set = { git = "https://github.com/timotree3/bit-set.git", branch = "fix-bit-vec-dep" }
```

I made my branch by finding the `0.2.0` source code adding this commit on top: https://github.com/timotree3/bit-set/commit/050fed0734794e98383ea13f928e0f66e056a28b

**Comment by maackle** [comment] 2021-09-16 18:43
I explored this too, and I also came to the conclusion that that `bit-set` is just so out of date that it's unsupported on the latest version of Rust. We'll need to fork it and/or have the maintainers fix it to be able to continue. Thanks for the fork @timotree3

**Comment by timotree3** [comment] 2021-09-16 19:44
By the way, bit-set is at version `0.5.2` now and the compile issue we're running into was fixed in `0.3.0`, I believe. The easiest solution would probably just be to update the bit-set dependency to the latest version (I just didn't do that at the time because the `0.2.0` dependency spans across other repos in the project.)

**Comment by maackle** [comment] 2021-09-17 18:48
I asked the maintainers of these crates for support
https://github.com/ptal/gcollections/issues/3
https://github.com/ptal/intervallum/issues/19

**Comment by ptal** [comment] 2021-09-20 08:12
I've merged the changes of maackle into the main repositories and updated the version numbers to 1.5.0 (gcollection) and 1.4.0 (intervallum). Should work now.

**Comment by maackle** [comment] 2021-09-24 19:28
#1003 uses the newly published dependency versions, and I've confirmed it builds with rust 1.55. Once it's merged we'll be back up to date with stable. Thank you @ptal!

**Closed** 2021-09-24 22:37 UTC
Labels: build issue
