### ISSUE TITLE
Efficiently get unread messages

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#4110] opened 2024-07-20 17:12 UTC
Assumption: small DHT so full sync

Efficiently get unread messages.

Proposed solution:

1. Each message is an entry and gets linked to a TimeUnit path, i.e. something like the path is a string of the the Year/Month/Week.
2. Retrieval of messages zome call is: getMessageHashesForTimeUnit(timeUnit, messageCountIAllreadyHaveForThisUnit) -> {countInTimeUnit, listOfHashesInTimeUnit}
3. UI stores count for timeUnit, and does a Set operation on the hashes of the messages, and then does a second zome call: getMessagesForHashes(listOfHashes) -> {[key:ActionHash]:Message} for any hashes that it doesn't have for that timeUnit (which could even get stored in localStorage for a a number of TimeUnits into the past.
Step 2 is implemented as first a count_links() call and then if the count doesn't match what was passed in a get_links() call.

[Thread in MM](https://chat.holochain.org/holo/pl/h783xuioafduuyamyk4zsg785w)

**Comment by ThetaSinner** [comment] 2024-07-22 12:01
Suggestion to add Local/Network get options to this call. That would bring it inline with other links functions and we could then provide both behaviors. I think both are actually wanted, and happy to discuss why.

**Comment by mattyg** [comment] 2024-11-30 00:17
Closing as duplicate of #4486 which more clearly outlines the necessary change.

The linked in MM notes that the original intent of `count_links` was to send only an integer over the network, rather than a list of action hashes. The original intent was the most lightweight possible check of freshness (i.e. I have less links than someone else thus I'm not fresh).

As I was the one who originally advocated for `count_links`, I'm satisfied with the current implementation. If others want to propose a change to the implementation for their specific need, they should do so in another issue.

**Closed by mattyg** 2024-11-30 00:17 UTC
