### ISSUE TITLE
[BUG] must_get_agent_activity fail with an unexpected InvalidCommit in tests

### ISSUE THREAD

**Issue by digitalillusion** [holochain/holochain#2421] opened 2023-05-24 09:25 UTC
**Describe the bug**
I have an issue validating integrity of agent activity during tests. The behavior to enforce is that an entry is created only once per agent; the code works well in the negative scenario (0 entries created yet), allowing the creation of the entry. However, when I attempt to create a second entry for the same agent (the positive scenario), I don't get the error I expect ( InvalidCommit error: An entry created by this agent already exists) but instead:

```sh
Unknown Error: undefined
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "data": {
    "data": "Source chain error: InvalidCommit error: [AnyDhtHash(uhCEkzDr-BcMUMMlnjMxoqhcg6C5Z58zgvyVIY78JzJ4Vnbo6mJpP)]",
    "type": "internal_error",
  },
}
```

**Expected behavior**
The expected error message would instead be, for tests as well, according to Rust code:

```rust
Ok(ValidateCallbackResult::Invalid(String::from(
            "An entry is already associated to this agent",
        )))
```

**System information:**
 - OS: Fedora 37
 - holochain (holochain 0.1.4): ac50baed6b53e9d0552729e69e1e20312e4edc08
lair-keystore (lair_keystore 0.2.3): cbfbefefe43073904a914c8181a450209a74167b
hc-launch (holochain_cli_launch 0.0.12): 1ad188a43900c139e52df10a21e3722f41dfb967
hc-scaffold (holochain_scaffolding_cli 0.1.7): c245d306110f3a5408f1dbe15d6a3725884ef3f4
{"git_info":null,"cargo_pkg_version":"0.1.4","hdk_version_req":"0.1.2","hdi_version_req":"0.2.2","timestamp":"2023-04-17T16:32:49.826057822Z","hostname":"localhost","host":"x86_64-unknown-linux-gnu","target":"x86_64-unknown-linux-gnu","rustc_version":"rustc 1.66.1 (90743e729 2023-01-10)","rustflags":"","profile":"release"}

**Steps to reproduce**
Minimal reproduction example available: https://github.com/digitalillusion/test_hc/actions/runs/5045324947/jobs/9049453604#step:5:951

1) [Add `must_get_agent_activity` call in entry creation validation](https://github.com/digitalillusion/test_hc/blob/main/dnas/test_float/zomes/integrity/float_rounding/src/float_rounding_entry.rs#L11)

2) [Call entry creation from tests
](https://github.com/digitalillusion/test_hc/blob/main/tests/src/test_float/float_rounding/all-float-rounding-entries.test.ts#L50)

**Additional context**
The error I expect is produced correctly when the HApp is running and the same code is executed by UI

**Comment by digitalillusion** [comment] 2023-05-24 10:39
It seems the problem is related to the action passed as top of chain in the `ChainFilter`.
```rust
 must_get_agent_activity(
            action.author().clone(),
            ChainFilter::new(action.prev_action().clone()),
  )?
```
Turns out that if there were previous write actions on the chain, the code above works. If the action that is validated by `must_get_agent_activity` is the first write (as in my tests) the unexpected error occurs.

As seen in this build, creating an entry on the chain before calling the create validated by `must_get_agent_activity`, allows the test to pass: https://github.com/digitalillusion/test_hc/actions/runs/5067612426/jobs/9098862376

**Comment by ThetaSinner** [comment] 2023-05-24 12:44
@maackle do you have any ideas about what is happening here? I can reproduce the issue by running these tests locally and the happ code looks right to me. I can also see some changes have been made to the relevant Holochain code for `0.2` so I'm wondering if this might be something that's already been fixed on `0.2`?

**Comment by maackle** [comment] 2023-05-26 22:49
I'm not quite clear on the issue. Is it just that the error message is different from what is expected? Or is it also that an error is not being thrown when it should be, or is being thrown when it should not? Are there perhaps multiple issues here?

For the first issue, perhaps it's just a matter of making the conductor return the actual reason for validation failure when doing a source chain commit with an invalid entry. But I could use more clarity on any other issue there might be.

I'll also try running locally when I get a chance.

**Comment by digitalillusion** [comment] 2023-05-28 03:32
I understand that my presentation of the problem may not have been clear enough so I will try to summarize my investigation so far: 

`must_get_agent_activity` ALWAYS fails with `InvalidCommit error: [AnyDhtHash(...)]` when the agent triggers this validation as his first action on the chain. If the validation is preceded by another action by the same agent (a read or a write which is NOT validated by `must_get_agent_activity`) then the function behaves correctly.

**Comment by ThetaSinner** [comment] 2023-12-06 19:51
@jost-s You've been looking at these `must_get_`s recently, I wonder if anything jumps out at you on this one? Maybe something that we might have resolved by now, or have an idea what's wrong?

**Comment by jost-s** [comment] 2023-12-06 20:12
Perhaps something to do with the scratch space not considered during validation? But that would be the same issue if you created another entry first before creating one with the must_get validation.
Another thought that comes to mind is that the zome initialization is involved. I don't know how, but that's one of the difference between running the validation on the first entry or a subsequent entry.

Feel free to assign this issue to me for investigation.

**Comment by jost-s** [comment] 2024-05-12 23:50
I cannot reproduce the error using the latest Holochain 0.3.0 or 0.4.0 release as evidenced with [this test](https://github.com/holochain/holochain/blob/fix/app-validation-retrigger-when-multiple-ops-missing-same-hash/crates/holochain/tests/regression/must_get_agent_activity_saturation.rs#L12) ran successfully on a pipeline here https://github.com/holochain/holochain/actions/runs/9054914937/job/24875304538?pr=3841#step:4:3007.

That test immediately starts creating entries that are validated with a must_get_agent_activity call. I tried to run that test against 0.1 but would have to backport several things. Please try your scenario again with a current version of Holochain.

Apologies for taking so long to respond to this issue!

**Comment by jost-s** [comment] 2024-06-21 03:12
I'm closing this issue. Please re-open it if the problem persists with a current version of Holochain.

**Closed by jost-s** 2024-06-21 03:12 UTC
