### ISSUE TITLE
Update coordinators developer journey is incomplete

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3301] opened 2024-02-05 09:56 UTC
As a happ developer, I have deployed [this app](https://github.com/darksoil-studio/rostanga) and some users have it already installed it in their computers, that is, they have a conductor running that has installed [the gather holochain app](https://github.com/darksoil-studio/gather). Now I'm in the process of iterative feedback cycles to keep improving the app. For that, I'm changing both the UI and the coordinators, so that the dna hash does not change. In this process I'm finding a lot of friction.

[`UpdateCoordinators`](https://docs.rs/holochain_conductor_api/latest/holochain_conductor_api/enum.AdminRequest.html#variant.UpdateCoordinators) takes a [`CoordinatorBundle`](https://github.com/holochain/holochain/blob/c4c0c9ee601ee5d99453e73308f0d1f5809986b0/crates/holochain_types/src/dna/coordinator_bundle.rs#L22), but there is no actual `hc coordinators pack` command or anything like it in the `hc` CLI tool. Moreover, the thing I would like to package together is "a set of coordinators that need to be updated **for each role in my app**, and an updated UI", as both things are interdependent. So maybe we need a new type of bundle for this? We could reuse `WebAppBundle` but that also brings all the integrity zomes and dna modifiers in it, so I'm not sure it's the best format for this. 

I would love to have something like a `WebCoordinatorsBundle` that specifies everything that needs to be updated in an app, without needing to specify the dna hashes, but only the role names. This bundle should be produced by the `hc` tool most likely, but not integrated in the conductor api, but rather the holochain runtime that handles web happs (launcher, kangaroo, we) should take it and update the UI, and then send the `UpdateCoordinators` call to the conductor. So [exactly like `WebAppBundle` in this sense](https://github.com/darksoil-studio/rostanga/blob/10a3467fcaa0a01779fa15bfd6275a4bcfa39de9/tauri-plugin-holochain/src/commands/install_web_app.rs#L29).

So from all of this experience, I think these would be my proposals:

1. Expand the `CoordinatorsBundle` to be a map of "Role name -> List of coordinators to update", so have it be at the app level instead  of the DNA level which is where it's at right now.
2. Create a new `WebCoordinatorsBundle` (I don't really like the name but it's descriptive) that can package a `CoordinatorsBundle` plus a UI, [really similar to `WebAppBundle`](https://github.com/holochain/holochain/blob/c4c0c9ee601ee5d99453e73308f0d1f5809986b0/crates/holochain_types/src/web_app/web_app_manifest/web_app_manifest_v1.rs#L17).
3. Update the `UpdateCoordinators` call to be about an app rather than about a DNA. I would also be fine to have two alternative calls, one for apps, and the other for DNAs, but it seems like the whole of the admin conductor API revolves much more around apps than around DNAs so it feels quite weird for `UpdateCoordinators` to be about DNAs. Can anyone figure out a use case in which you don't want to change the coordinators for all the DNAs in an app, but just for that one DNA?

cc @matthme @mattyg @maackle @abe-njama

**Comment by guillemcordoba** [comment] 2024-02-05 10:14
I just thought of another thing that moving `UpdateCoordinators` being about DNAs to being about roles fixes: cloned cells. I would want `UpdateCoordinators` to update all the coordinators for all the clones for a specific role, and right now I guess I would have to iterate over all the clones and their dna hashes and update them? I don't even know if I would need to do that.

**Comment by matthme** [comment] 2024-02-05 10:55
Oh yes, the cloned cell case seems like quite a crucial one to be supported. I just had another idea - how about "UpdateCoordinators" would accept a full happBundle as well as an installed_app_id as input and holochain does the unpacking and updating for all cells of that app under the hood? Then you'd not need to bother about packaging a "CoordinatorBundle" in the first place. One case that would need to be covered is if the integrity zome hashes don't match up, whether that's okay or throws an error...

**Comment by matthme** [comment] 2024-02-05 10:56
That would maybe need to become a separate call `UpdateAppCoordinators`, additional to the existing `UpdateCoordinators`.

**Comment by guillemcordoba** [comment] 2024-02-05 11:08
Hum... I just had a case in which in the code I only updated one coordinator zome, and then bundled the app together and [updated the coordinators with the existing call comparing the hashes of the new and old coordinators](https://github.com/darksoil-studio/rostanga/blob/5858d46248c380f20b0d62879702dbf3a3cb8277/tauri-plugin-holochain/src/commands/install_web_app.rs#L162). To my surprise, all the coordinators were updated. I found out later that I recompiled the wasms and run `wasm-opt` on them again, which made the files slightly different because that process is not deterministic, so comparing hashes with code recompilation doesn't really work.

I think this is a significant foot gun, and this is why I'm in favor of being really explicit about the actual wasms that you want to update. If I had implemented the check of integrity zomes and their hashes, the check wouldn't have passed... Because the actual hashes are different. Using `WebAppBundle` this way also means sending a whole lot of bytes around that are most likely not needed (like all the integrity zomes for example).

On our side (happ devs) I think we need to add some tooling to our apps to handle this (like `npm run package`, but for non-dnahash-breaking updates).

**Comment by matthme** [comment] 2024-02-05 11:16
> why I'm in favor of being really explicit about the actual wasms that you want to update

I see how that's desirable in your case where you have full control over both the webhapp and the runtime (although does it really matter if you update a coordinator zome that didn't actually change apart form its hash due to non-determinism in the compile step?). In case of a runtime like the launcher this explicitness is not really of much use I think because whether and which coordinator zomes need to be updated needs to be determined automatically anyway (i.e. based on wasm hashes) since the app has been built by someone else.

**Comment by guillemcordoba** [comment] 2024-02-05 11:20
Hum I don't know that I understand what you are saying. In my proposal, you would only bundle the zomes that actually changed, so that's much less bytes transferred over the wire, and much less time waiting for the app to update. On computers, one of the bottlenecks for things like the DevHub is the time it takes to download the apps. On mobile phones, that's also a big bottleneck, but the biggest one is time waiting for the zomes to get installed. I see this affecting the performance and efficiency of all holochain runtimes, and specially if they target mobile. Wouldn't you want to download a much lighter bundle from the devhub to update an app in the launcher?

**Comment by matthme** [comment] 2024-02-05 13:28
Okay, yes I did not consider the limitations that you are talking about (installing wasms on mobile and transferring bytes from devhub). I think that's partly because the latest devhub iteration has been built around the assumption that whenever a developer uploads something, they upload a full webhapp (which has been informed by simplicity in the uploading UX but has never really been talked through).
Still, I'm not sure I would want the specification about which coordinator zome(s) need(s) to be updated to be a hard requirement but rather something optional and if not specified, it gets inferred from wasm hash differences.

Apart from there being a cost to transferring the full webhapp or coordinator bundle over the network, I think there is also a cost (and sources of errors) to not derive the information about what changed from wasm hashes and instead put the responsibility to the developer to somehow specify this and keep track of that information in the devhub. Deriving changes from hashes just seems more fool-proof to me but maybe that could be done at the time of uploading and then still only what actually changed based on hashes would be fetched.

**Comment by maackle** [comment] 2024-02-06 19:09
@guillemcordoba your proposals make sense. We do all other cell management in the conductor at the app level, not the DNA level, so coordinator updates should be the same.

I don't want to derail this conversation but I feel like a few times a year I want to ask the big questions to make sure we're still on track, and this seems like a good time to ask: Are coordinator zomes still working for us, and are they still what we want?

The alternative to coordinators of course would be doing all coordination from the UI -- then updating your "coordinator" would be as simple as updating the UI, which is already a solved problem. We could make all HDK calls accessible from the UI, including the ability to specify transactional commits.

If it is really useful to have coordinator zomes, then we do have to do the work you mention, and think through to make sure it solves all cases.

**Comment by guillemcordoba** [comment] 2024-02-06 19:52
Hum... good questions... I think there are some cases specially with headless nodes providing services (notification providers, file storage providers, indexing providers) where I think it's absolutely necessary since they don't actually have UI. I actually just implemented a push notifications service app that takes advantadge of this very fact, so that different providers can co-exist in the same DNA but implement very different functionality: https://github.com/darksoil-studio/notifications/blob/12c6c2a5e671c30fa85b5647475f489ad9a8b01a/providers/fcm/apps/notifications_provider_fcm/dnas/notifications/workdir/dna.yaml#L17 . So in this case each different provider packs different coordinator zomes.

**Comment by maackle** [comment] 2024-02-06 20:23
Yeah I guess one of the main benefits is that the code can be bundled with the app in a known execution environment, so once you have the app you have everything you need to run it. Even "headless" apps have to be installed by something, and that same installer could also do initialization. But then that execution context would be something other than Holochain which isn't ideal.

I'll ask again in a year ;)

OK so do you/some people want to create a spec for how this update should look? Maybe create a sample yaml file, sample admin request/response, and some bikeshedding on what to call this bundle?

**Comment by ThetaSinner** [comment] 2024-02-16 14:14
I'm wondering why we want a separate bundle and option for updating coordinators. This feels more like an operation than a completely isolated process.

If i've released an app at 1.1.2, then I make a small change and want to release it as 1.2.0 such that
- New users who don't have 1.1.2 installed can install 1.2.0
- Existing users can be sure they're going to stay in the same network because the integrity zomes aren't changing

Then what I really want is to distribute a full webhapp bundle and let users choose what to do with that bundle. Whether it's called `update_coordinators` or `update_app` I think the conductor should just accept the same information that `install_app` did and produce an error if the bundle provided would try to update integrity zomes.

I've talked about some similar ideas here https://github.com/holochain/holochain/discussions/2167, and looking through our list of issues we have several problems around install/update behavior. It seems like something that needs tackling sooner rather than later!

**Comment by guillemcordoba** [comment] 2024-02-16 18:33
Hmmm yeah... Except that the compiling process from rust to wasm and running `wasm-opt` on the wasms is not deterministic, so actually the integrity wasms' hashes will have changed even if I don't change any code in it. So this seems like a big foot gun to me, that devs bundle the same integrity zomes thinking it ought to work but they have a different hash so it breaks. Separating it into two bundles allows devs to be much more explicit about this, and it also means that much less bytes need to be uploaded and downloaded from the devhub for example when downloading an app, as you already know that you are only changing the non-integrity part of your app a priori.

Another idea that I had in a conversation with @matthme is to deprecate `WebAppBundle` altogether and superseed it with two types of bundles: `AppBundle` and `WebCoordinatorsBundle`, where in `AppBundle` there is no way to specify Coordinator zomes, only integrity zomes allowed. And then `WebCoordinatorsBundle` only includes the coordinators and the web UI, which are the things that are tightly bound together. Then when you publish an app, you publish its appbundle and the first web coordinators bundle, and when you want to update ui/coordinators, you just publish a new version of the `WebCoordinatorsBundle`. The `WebCoordinatorsBundle` would maybe include the hash of the `AppBundle` that it's supposed to be dependent on.

Although thinking more about all of this, I think we should include in the discussion the different strategies by which an update in the code of integrity zomes can be handled, because that would likely influence the type of bundles that exist. For example, what if I have an app with 4 DNAs, and only one of them has changes in its DNA? I don't want to install the app again as that would duplicate the 3 DNAs, and there is no migration needed in them, and even trying to do that with the same public key will result in a "duplicate cell id" error so I can't go that way. In the current state of holochain I would be a bit stuck, there is no way to say "replace this DNA in this app with this other one", and it's very weird to release a new app with only that one DNA changed and migrate all data to that one, and I would be left with two apps instead of one, and the cell for the previous version of that DNA would still be running as there is no way to disable it or delete it if it's not a clone.

I am beginning to hit the current limits of the current state of affairs with updates and migrations, so I have energy to discuss it and options on how to do it.

**Comment by matthme** [comment] 2024-02-19 13:32
I would also be interested in making progress on this topic soon as we're having to deal with those questions when integrating devhub/appstore with launcher and We. Maybe we should create some sort of working group around this?

**Comment by maackle** [comment] 2024-02-19 18:31
Yes please to a working group! @guillemcordoba and @matthme are highly engaged with this functionality and are well poised to propose something that will work well. I'm happy to be part of the group to help with implementation and integration but the design and specs should be driven by app devs like you. Please take our app ontology to the next level.

I like the direction of what's been proposed so far, like splitting up the integrity and coordinator parts of the app bundle, and also the thinking through how to update some but not all DNAs in an app. Sounds like the whole app functionality needs to be conceptually taken apart and put back together. I would suggest coming up with what seems like the ideal solution regardless of implementation and then we can figure out if we want to make compromises to not change things too drastically.

Is there anything you need to feel motivated to get started on this? Like help structuring the working group and its goals, or a commitment of holochain core team resources to make sure whatever you come up with is implemented in a timely fashion?

**Comment by maackle** [comment] 2024-02-19 20:24
And I don't mean to single out those two as the devs who should take this on but they're the ones active in this thread, others should chime in too if there's motivation

**Comment by nphias** [comment] 2024-02-21 23:40
I think in facing non-dnahash-determinism and part-happ upgrade complexity ... i would be more in favour of it being a migration approach.. even if you make a small change to coordinators, its a new version.
I would also like to see a unique signature hash for the entire zome pack..   so that you can verify the work as intended by the author..    
I feel that the coordinator integrity dividend is helpful so that devs can reason about what needs validation and immutability and what doesn't.   A migration process while running both versions should be far simpler if only the coordinators have changed..  A "light" migration

**Closed** 2024-11-20 16:32 UTC
Labels: permanent
