### ISSUE TITLE
[BUG] Conductor warning "failed to resolve stun host"

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2740] opened 2023-09-05 17:38 UTC
**Describe the bug**
I regularly get this conductor warning:
```
WARN[0m tx5_go_pion_sys: failed to resolve stun host: turn.holo.host:443: lookup turn.holo.host on 127.0.0.53:53: no such host
```

Does this indicate it's trying to connect a signal server on my local network? Not sure if this is expected but it doesn't make sense to me.

**Expected behavior**
It tries to connect to the signal server on some remote IP.

**System information:**
 - OS: Ubuntu 22.04
 - Browser: n/a
 - Holochain and HDK Version: 0.2.1

**Steps to reproduce**
- Download mewsfeed happ: https://github.com/GeekGene/mewsfeed/releases/download/v0.10.0-rc.4/mewsfeed.happ
- Download holochain-runner: https://github.com/lightningrodlabs/holochain-runner/releases/download/v0.7.6/holochain-runner-x86_64-unknown-linux-gnu.tar.gz
- Run `echo "pass" | RUST_LOG=info ./holochain-runner $(pwd)/mewsfeed.happ --keystore-path $(pwd)/keystore $(pwd)/databases`
- View the output logs, you should see the warning appear within a few minutes.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by ThetaSinner** [comment] 2023-09-06 17:14
We've definitely seen this before but it does seem to be a transient problem. My main concern with this is what happens to the state within Holochain when these kinds of errors happen.

I believe we've had problems reproducing this before @neonphog but is there anything new we might be able to add to our understanding of this problem here?

Either way I'm happy to keep this open to track the problem until we get it resolved.

**Comment by neonphog** [comment] 2023-09-06 17:21
@ThetaSinner @mattyg - This isn't a real problem, but we ***do*** need a real solution.

WebRTC is a bit of a shotgun, it hits up DNS on every single interface on your system, and some of them report errors either because they're loopback or actually docker interfaces, or whatever other reason. The ones that respond correctly are used to actually connect to the TURN server, the others are ignored. So, you get the warning, ***and*** it's also working correctly at the same time.

But, it indeed looks bad in the logs, and when something else is not working it is a problem when people have to spend time dismissing this warning. Unfortunately, the warning is generated in the go pion webrtc library we are using. Short of doing a string identification on it, I'm not sure how to suppress it, and if you actually do not have DNS access on any of your local interfaces, so it is actually a real problem, it might be bad if we were suppressing it.

Does anyone have any additional thoughts/suggestions for this?

**Comment by ThetaSinner** [comment] 2023-09-07 10:13
If I were the library author for the Go code I'd be looking at doing something like capturing errors while running through possible interfaces and only log when you have either
- found some that work and log those; or
- found none that work and dump what was tried. 
So by default a few problem interfaces can just be ignored.

Is it worth sharing this question with the library authors and seeing what they suggest?

**Comment by neonphog** [comment] 2024-06-13 14:16
We have since (on develop / 0.4) added [this tuning_param](https://github.com/holochain/holochain/blob/4be2cfa4aa5d92dcea35f76aff344af5127e07fb/crates/kitsune_p2p/types/src/config.rs#L276-L277) which defaults to off (i.e. it no longer displays these internal backend webrtc traces). So I think we can, in fact, close this as complete.

Please feel free to re-open if this is still experienced.

**Closed by neonphog** 2024-06-13 14:16 UTC
