### ISSUE TITLE
“link error: Import not found, namespace: env, name: __debug”

### ISSUE THREAD

**Issue by dellams** [holochain/holochain#736] opened 2021-04-16 12:59 UTC
Hi Guys,

I managed to finally get the RSM conductor working in WSL2 but when I tried running the elementalchat happ it worked the 1st time but the 2nd time I got this error:

```
[nix-shell:~/holochain-rsm2/elemental-chat-develop/elementalChatHapp]$ hc sandbox generate ElementalChat.happ
hc-sandbox: Creating 1 conductor sandboxes with same settings
hc-sandbox: Config ConductorConfig { environment_path: EnvironmentRootPath("/tmp/tmp.xqmx7dSJtZ/VS7ZNAipLD2AIFCFc3fnP"), use_dangerous_test_keystore: false, signing_service_uri: None, encryption_service_uri: None, decryption_service_uri: None, dpki: None, keystore_path: Some("/tmp/tmp.xqmx7dSJtZ/VS7ZNAipLD2AIFCFc3fnP/keystore"), passphrase_service: None, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 0 } }]), network: None }
hc-sandbox: Created directory at: /tmp/tmp.xqmx7dSJtZ/VS7ZNAipLD2AIFCFc3fnP Keep this path to rerun the same sandbox
hc-sandbox: Created config at /tmp/tmp.xqmx7dSJtZ/VS7ZNAipLD2AIFCFc3fnP/conductor-config.yaml

Conductor ready.
Error: Failed to install app: Expected AdminResponse::AppBundleInstalled but got Error(InternalError(“Conductor returned an error while using a ConductorApi: EntryDefStoreError(DnaError(WasmError(Compile(“link error: Import not found, namespace: env, name: __debug”))))”))
```

Any ideas guys? I asked on the forum 23 days but didn't get a response, so is it better for me to ask here for quicker turn aorund times? :)

Cheers
D.

**Comment by artbrock** [comment] 2021-06-18 15:51
@dellams, Did you get an answer on the Forum or elsewhere for this?

Also, are you using [wasm-opt](https://github.com/WebAssembly/binaryen#tools) to compile your wasms? We highly recommend it.

We should be releasing a new version of Holochain today, so it would be great if you could retry with the current set up and try using wasm-opt for your compiling.

-art

**Comment by ThetaSinner** [comment] 2023-04-12 16:49
@dellams did you get a chance to try this on a newer version of Holochain?

**Comment by ThetaSinner** [comment] 2023-10-03 12:15
These kinds of errors are usually caused by version mismatches of some kind in code that gets fed into the WASM compile. In general you're looking for mismatches between the happ libraries and the conductor. The best people to debug that kind of problem will usually be hApp authors.

I'm going to close this issue because of it's age. If you run into this again please open a new issue.

**Closed by ThetaSinner** 2023-10-03 12:16 UTC

**Comment by dellams** [comment] 2023-11-06 22:59
Hey guys! 

Really sorry I only just seen this buried in my inbox! I presume this has been resolved now? I will give this a go with the latest hc... is elemental chat updated to the latest version? Im currently still on 0.1.5 because I am upgrading HoloNET to work against that version before updating to the latest version... :)

**Comment by dellams** [comment] 2023-11-06 23:09
> Also, are you using [wasm-opt](https://github.com/WebAssembly/binaryen#tools) to compile your wasms? We highly recommend it.

@artbrock Are you guys still using this? If so, I will look to see if there are any .net integrations I can use for the .NET HDK I am working on... thanks! :)
