### ISSUE TITLE
[BUG] Admin websocket connection fails with "too many open files" error on MacOs.

### ISSUE THREAD

**Issue by matthme** [holochain/holochain#1666] opened 2022-11-23 16:27 UTC
**Describe the bug**
I'm not sure whether this can be classified as a bug but it seems quite critical that Holochain is able to deal with this scenario:
On MacOS it can quite regularly [occur](https://github.com/holochain/launcher/issues/65) that a connection to the Admin Websocket fails with this error:

```
[2022-11-15T18:27:29.528613+13:00] INFO - [HOLOCHAIN 0.0.162] Nov 15 18:27:29.528  WARN holochain::conductor::interface::websocket: Admin socket connection failed: Too many open files (os error 24)
```
This can be solved by increasing the ulimit like for example described here: https://mampsupportforum.com/viewtopic.php?t=155

However, since this error is not forwarded to the UI in any way (could this added to the js and rust clients?) it is impossible for a UI to give the end-user a useful error message and all he sees is that the hApp doesn't work and a connection to the conductor cannot be established. Furthermore it seems to me that we cannot expect end-users to solve that problem themselves as it requires quite some technical expertise to increase the systems ulimit.

**Expected behavior**
Holochain respects the system-defined ulimit and if a connection to the admin websocket fails with "too many files open", Holochain takes measures to reduce the amount of open files and re-establishes connection. 

**System information:**
 - OS: macOS
 - Browser Tauri Window / Firefox but it doesn't matter
 - Holochain and HDK Version: Latest documented occurence with Holochain v0.0.162, HDK 0.0.152

**Steps to reproduce**
Install many apps in the Holochain Launcher on a system with a relatively small ulimit and try to start them.

**Screenshots**
-

**Additional context**
-

**Comment by Connoropolous** [comment] 2022-12-01 19:39
this is the main issue that I've seen prevent the (very big, many files) hREA .happ file from working well all the time in the Launcher. 

If you install the hrea_suite.happ file from the Sapling release to the Launcher, you will likely see this occur: 
https://github.com/h-REA/hREA/releases/tag/happ-0.1.0-beta

**Comment by abe-njama** [comment] 2023-03-20 09:51
@matthme This issue was resolved by rejecting pending connections when the websocket connection closes and making the error message more specific on the client. [Fix](https://github.com/holochain/holochain-client-js/pull/178).

**Comment by matthme** [comment] 2023-04-19 08:49
Sorry for responding late to this. For me this issue is not really addressed by fixing something in the js-client. Holochain cannot assume that people are using the official js-client (the DevHub for example is not using it, but uses [this one](https://github.com/mjbrisebois/holochain-client-js) instead). So to have that issue properly addressed, holochain would need to be able to deal with that scenario that was fixed in case of the official js-client. Otherwise, as soon as there is one app installed in the Launcher that introduces that problem, the Launcher as a whole becomes dysfunctional again.

I'm also not sure whether I can unambiguously test it because I don't know the exact circumstances that lead to the behavior. If it was indeed the js-client issue, what I can do is install a new Launcher and populate it only with apps that use the fixed js-client and then wait to see whether I still run into the problem. But this would probably not be sufficient to conclusively tell whether it was fixed.

**Comment by ThetaSinner** [comment] 2023-04-19 11:47
That makes a lot of sense to me, @matthme. I'm happy to keep this open and look at what we can do improve error mesaging and manage resource usage on the conductor.

If we're going to spend more time looking at the conductor for this issue then it'll need to be possible to reproduce it so we can take on responsibility for testing any improvements. In the meantime, it would be good to keep an eye out for it just. If it happens then it would be useful to have any additional information back that might be useful.

**Comment by ThetaSinner** [comment] 2023-04-24 18:14
I'm seeing this myself now running the live launcher with holochain `0.1.3`

```
[2023-04-24T19:12:41.040551+01:00] INFO - [HOLOCHAIN 0.1.3-Beta] [2mApr 24 19:12:41.040[0m [33m WARN[0m holochain::conductor::interface::websocket: Admin socket connection failed: Too many open files (os error 24)
```

**Comment by matthme** [comment] 2023-04-24 18:24
Hmm...would be good to know whether you have any apps with js-client before `0.12.4`. But I think that's likely since e.g. TalkingStickies' latest version on the DevHub still uses `0.12.1` I think.

**Comment by ThetaSinner** [comment] 2023-04-24 18:52
Talking stickies x2 yes plus of `place` x2 which is using `0.12.0` https://github.com/lightningrodlabs/place/blob/main/webcomponents/package.json#L27. So at least 4 apps with the potential to use up my resources.

Not having to rely on every user of the client library to upgrade before this can be resolved is a good enough reason to try and improve this in Holochain IMO

**Comment by ThetaSinner** [comment] 2023-06-02 12:55
I can reproduce this on Linux too. It takes longer but connections which aren't shut down properly will eventually (> 30k) prevent new connections from making calls. After that continuing to make connections (> 50k) will lead to new connections not being able to establish at all.

**Comment by ThetaSinner** [comment] 2023-06-05 17:48
I've put up a related PR #2461 which fixes an issue, I'm not certain its the same cause as this issue but I hope it will help. 

@alastairong I'm hoping the fix might help with the similar issue you reported but again, it's hope and not certainty!

**Comment by matthme** [comment] 2023-12-21 18:10
Just saw this error today in launcher (holochain 0.2.4-rc.0):
```
Error install hApp bundle: ExternalApiWireError(InternalError(\"Conductor returned an error while using a ConductorApi: AppBundleError(FfsIoError(IoError { original: Os { code: 24, kind: Uncategorized, message: \\"Too many open files\\" }, path: Some(\\"/var/folders/52/xfv3w7s535schg01cmb6b5380000gn/T/app_to_installSystemTime { tv_sec: 1703179478, tv_nsec: 628205000 }.webhapp\\"), backtrace:    0: <unknown>\\n   1: <unknown>\\n   2: <unknown>\\n   3: <unknown>\\n   4: <unknown>\\n   5: <unknown>\\n   6: <unknown>\\n   7: <unknown>\\n   8: <unknown>\\n   9: <unknown>\\n  10: <unknown>\\n  11: <unknown>\\n  12: <unknown>\\n  13: <unknown>\\n  14: <unknown>\\n  15: <unknown>\\n  16: <unknown>\\n  17: <unknown>\\n  18: <unknown>\\n  19: <unknown>\\n  20: <unknown>\\n  21: <unknown>\\n  22: <unknown>\\n  23: <unknown>\\n }))\"))
```
Looks like this issue may still not be resolved?

**Comment by maackle** [comment] 2024-01-05 23:33
\\"/var/folders/52/xfv3w7s535schg01cmb6b5380000gn/T/app_to_installSystemTime { tv_sec: 1703179478, tv_nsec: 628205000 }.webhapp\\"

That's quite the filename!

**Comment by abe-njama** [comment] 2024-01-08 13:27
This issue wasn't intended to be closed.

**Comment by steveej** [comment] 2024-01-12 13:07
> ```
> \\"/var/folders/52/xfv3w7s535schg01cmb6b5380000gn/T/app_to_installSystemTime { tv_sec: 1703179478, tv_nsec: 628205000 }.webhapp\\"
> ```
> 
> That's quite the filename!

indeed. i wonder if the error isn't misleading and it's actually a path issue.

**Comment by matthme** [comment] 2024-11-06 16:48
I have not seen it or heard of it lately no. Might be fixed in the meantime and we can close it for now until someone encounters it again.

**Comment by ThetaSinner** [comment] 2024-11-06 17:16
Thanks for confirming. Let's close this issue for now then and if it shows up again then we can open a new one

**Closed by ThetaSinner** 2024-11-06 17:16 UTC
