### ISSUE TITLE
if holochain is launched without an internet connection, cells do not begin to gossip once that internet connection has been restored

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1580] opened 2022-09-19 17:30 UTC
"Yeah I think that's the issue but it's not about the AdminWebsocket itself. When the conductor starts, it tries to boot up all the cells, and in that process goes to the bootstrapping service to get the nodes. If it can't reach the bootstrapping service which is hosted in cloudflare, it pauses the app. This needs to change in holochain core I think."

_Originally posted by @guillemcordoba in https://github.com/holochain/launcher/issues/78#issuecomment-1251317588_

I will work on adding a clearer 'steps to reproduce', but the basics are: 
1. shut off your internet
2. start holochain

**Comment by maackle** [comment] 2022-09-21 00:45
I wonder what the expected outcome should be. Silently fail and retry with exponential backoff?

**Comment by kaichaosun** [comment] 2022-09-21 02:52
I expected there are two options for agents to choose, with [local first design](https://www.inkandswitch.com/local-first/) in mind,
- manual, agent could decide to open and close the network connection capability for holochain when start it, and save the flag to config file for next restart. If agent open it, but the network is offline or bootstrap nodes is blocked (I have always seen this), agent should be notified the warn messages, here retry can also be made as a manual operation in launcher.
- auto, close and open the connection capability of holochain based on the device network accessibility, here auto retry makes more sense to me, a clear signal in launcher show the connection status will be handy.

One question is how can the pending entries be spread into DHT after network connection comes back, is there a queue or something similar? I'll interested in the implementation details.

**Comment by Connoropolous** [comment] 2022-09-21 20:27
"Silently fail and retry with exponential backoff?"
what will the immediate implications be? that no peers can be discovered via the service, obviously I guess. anything else?

I'd say your proposed sounds about right to me

**Comment by matthme** [comment] 2022-09-22 05:53
I don't know how exponential backoff is currently implemented but for this use case I would say there should probably be a "plateau" in the retry-frequency below which it won't fall, since the user can be expected to get back online anytime.
Or maybe something like a periodic ping to the bootstrap server to check for connection and whenever the ping succeeds retry?

**Comment by maackle** [comment] 2023-01-03 19:54
Yeah, it should probably be more like a periodic ping. Every 5-10 seconds.

**Comment by Connoropolous** [comment] 2023-01-03 20:19
Yeah, it should definitely be persistent in trying

**Comment by Connoropolous** [comment] 2023-01-05 03:22
I saw this in todays dev pulse. 
<img width="1289" alt="Screenshot 2023-01-04 at 7 22 16 PM" src="https://user-images.githubusercontent.com/1409121/210694532-050a581a-2bad-4dd5-9931-e57e0cfc5316.png">

I will take a look into a useful steps to reproduce

**Comment by Connoropolous** [comment] 2023-01-05 03:24
I believe a revised outline would be:

I will work on adding a clearer 'steps to reproduce', but the basics are:

- start holochain
- install an app
- shut down holochain process
-  shut off your internet
 - start that same holochain process, the one with an installed and enabled

**Comment by Connoropolous** [comment] 2023-01-05 03:25
tagging you @pdaoust , just so you're aware

**Comment by Connoropolous** [comment] 2023-01-05 03:26
I think it's possible that holochain-runner specific code is the bit erroring out when an internet connection is down, during launch. 

Of course, I see these in the logs, but I am not totally certain they are throwing a fatal exception
```
ERROR kitsune_p2p::spawn::actor::space: msg="Failed to get peers from bootstrap" e=Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("bootstrap-staging.holo.host")), port: None, path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) })
```

**Comment by Connoropolous** [comment] 2023-01-07 01:30
We should look more closely into @matthme description of the issues faced with Holochain Launcher... 
it appears that there is a way to resolve, within holochain-runner, holochain-runner failing on boot when lacking an internet connection. The issue was related, but was a misdirection from this issue.

**Comment by Connoropolous** [comment] 2023-01-07 01:30
Matthias describes: 
"To Reproduce
Steps to reproduce the behavior:
    Start the launcher without internet connection
    Apps are paused and cannot be opened
"

**Comment by Connoropolous** [comment] 2023-01-07 03:02
I have confirmed the following with Acorn:
- due to the changes we made to the holochain-runner code, we can launch without an internet connection. My apologies for the misleading issue title
- when starting up, even with no internet, zome calls to cells within apps go through to holochain and it replies
- what I observe is that once I turn the internet back on, the cells still do not begin to gossip or network. I am assuming that this is now the part of the concern that may be relevant to refocus this issue on

**Comment by Connoropolous** [comment] 2023-01-07 03:05
I have renamed the issue " if holochain is launched without an internet connection, cells do not begin to gossip once that internet connection has been restored "
please let me know if other concur with that assessment

**Comment by matthme** [comment] 2023-01-10 15:48
I did some more in-depth debugging with the launcher now and here is what I found. I tried the two combinations
* `start Launcher offline > get online`
* `start Launcher online > get offline > get back online`

During all that period I had both the js-client and the rust-client call `listApps` in regular intervals.

### **`offline > online`**:
1. Launcher starts up and both js-client and rust-client return status `Paused` for apps
2. holochain logs show messages of this kind in frequent intervals:
```
[2023-01-10T16:23:36.076300446+01:00] INFO - [HOLOCHAIN 0.1.0-beta-rc.2] Jan 10 16:23:36.074  WARN quinn_udp: sendmsg error: Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }, Transmit: { destination: 137.184.142.208:5788, src_ip: None, enc: Some(Ect0), len: 1200, segment_size: None }
[2023-01-10T16:24:00.378582814+01:00] INFO - [HOLOCHAIN 0.1.0-beta-rc.2] Jan 10 16:24:00.378 ERROR kitsune_p2p::spawn::actor::space: msg="Failed to get peers from bootstrap" e=Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("bootstrap.holo.host")), port: None, path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) })
```
3. turn online
4. After a while, holochain logs seem to indicate that gossip has actually started with logs like these:
```
[2023-01-10T16:26:42.119673750+01:00] INFO - [HOLOCHAIN 0.1.0-beta-rc.2] Jan 10 16:26:42.119  WARN kitsune_p2p::spawn::actor: failed to handle incoming delegate broadcast err=Other(OtherError("no remote nodes found, abort discovery"))
```
and later these:
```
[2023-01-10T16:26:51.643619058+01:00] INFO - [HOLOCHAIN 0.1.0-beta-rc.2] Jan 10 16:26:51.643  WARN kitsune_p2p::metrics: Recorded initiate with current round already set

```
4. Both the js-client and the rust-client keep returning app status `Paused` for the apps.


### **`online > offline > online`**:
1. Launcher starts up, js-client and rust-client return status `Running` for the apps and gossiping seems to be active according the logswith logs like these:
```
[2023-01-10T16:28:37.548355270+01:00] INFO - [HOLOCHAIN 0.1.0-beta-rc.2] Jan 10 16:28:37.548  WARN kitsune_p2p::metrics: Recorded accept with current round already set
```
2. Turn offline
3. Gossip seems to stop, i.e. no such logs from kitsune_p2p anymore, then timeout errors from `kitsune_p2p::gossip::sharded_gossip` and after a while the network unreachable error:
```

**Comment by matthme** [comment] 2023-01-10 15:52
Accidentally closed while editing markdown, sorry. It's hard to keep up the discipline to hit `Shift + Enter` instead of `Enter` all the time :)

**Comment by matthme** [comment] 2023-01-10 17:52
I did some more testing to verify that gossiping does indeed work despite the status remaining `Paused`. It looks like that's the case (although it may take quite long sometimes until data is transmitted after getting back online) - except for one edge case. Namely, when an app has been installed offline and never seen the network in its "lifetime" yet. In this case, it seems that it won't start gossiping ever after getting online and only a restart of the Launcher, i.e. conductor makes it actually connect and be able to get the data.

**Comment by Connoropolous** [comment] 2023-01-10 18:07
"Namely, when an app has been installed offline and never seen the network in its "lifetime" yet. In this case, it seems that it won't start gossiping ever after getting online and only a restart of the Launcher, i.e. conductor makes it actually connect and be able to get the data."
This is consistent with my Acorn test

**Comment by maackle** [comment] 2023-01-16 16:24
> I did some more testing to verify that gossiping does indeed work despite the status remaining Paused

this may actually be due to a bug though, which will be fixed by #1761, so we can't rely on that behavior continuing.

It sounds like we should simply never pause a cell due to being "offline", does that sound right? Behind the scenes the cell should continue to try to reach the bootstrap server and its peers, but the user should be able to use the app normally.

There should eventually be warning about being "offline" that UIs can display, but there's a whole spectrum of "onlineness" that we probably want to convey: totally disconnected -> can see some peers on local network -> can see some peers on internet (possible eclipse attack?) -> can see some but not all of the "usual" peers (netsplit?) -> can see bootstrap and many peers ("fully online")

**Comment by Connoropolous** [comment] 2023-01-16 16:25
"It sounds like we should simply never pause a cell due to being "offline", does that sound right? "
sounds very right to me

**Comment by matthme** [comment] 2023-01-16 16:30
> this may actually be due to a bug though, which will be fixed by https://github.com/holochain/holochain/pull/1761, so we can't rely on that behavior continuing.

So that they start gossiping again after getting back online despite having status "Paused" may be caused by the bug? In this case I agree that we should never pause a cell due to being offline.

**Comment by Connoropolous** [comment] 2023-01-24 18:34
@matthme have you tested to see if this is resolved now?

**Comment by matthme** [comment] 2023-01-26 09:59
It's not resolved yet I think.

**Comment by maackle** [comment] 2023-07-21 17:27
Without having looked into it, from this conversation, it sounds like a remaining problem might be the fact that cells are paused if they can't join the network. One outcome of this thread is that cells should never be paused just because they're "offline". Not sure if that's still the case but this line seems to make me think it may be https://github.com/holochain/holochain/pull/2419/files#diff-3ef542bca2aca33843a6f5a04e181768fcb23e2b85e161be9ee27dd45a7b28e9R2005

**Comment by maackle** [comment] 2023-12-06 00:20
@ThetaSinner is this potentially (partially, wholly?) fixed by the bootstrap connection retry you added? Do cells which are paused attempt to get running again upon bootstrap connection?

**Comment by ThetaSinner** [comment] 2023-12-06 13:07
I think so but with that change released, we are still hearing that this isn't working as desired. When I retested this morning starting Holochain up with a hApp installed in the sandbox and using tx5 with bootstrap I see

```
msg="Some cells did not start" app=InstalledApp { app: InstalledAppCommon { installed_app_id: "test-app", agent_key: AgentPubKey(uhCAkPKFzZMxJ6_QHIA01Rlm7dF4tm-Lo9iprj9Ooc23zdr2KBtoA), role_assignments: {"drone_swarm": AppRoleAssignment { base_cell_id: CellId(DnaHash(uhC0k1i9iRCaFuwvycaj5QN9DhwjMi08sQAlHwMHx7xuZJtgch2VB), AgentPubKey(uhCAkPKFzZMxJ6_QHIA01Rlm7dF4tm-Lo9iprj9Ooc23zdr2KBtoA)), is_provisioned: true, clone_limit: 0, next_clone_index: 0, clones: {}, disabled_clones: {} }}, manifest: V1(AppManifestV1 { name: "drone-swarm", description: None, roles: [AppRoleManifest { name: "drone_swarm", provisioning: Some(Create { deferred: false }), dna: AppRoleDnaManifest { location: Some(Bundled("../dnas/drone_swarm/workdir/drone_swarm.dna")), modifiers: DnaModifiersOpt { network_seed: None, properties: None, origin_time: None, quantum_time: None }, installed_hash: None, clone_limit: 0 } }] }) }, status: Running } missing=[CellId(DnaHash(uhC0k1i9iRCaFuwvycaj5QN9DhwjMi08sQAlHwMHx7xuZJtgch2VB), AgentPubKey(uhCAkPKFzZMxJ6_QHIA01Rlm7dF4tm-Lo9iprj9Ooc23zdr2KBtoA))]
```

Which gets logged every 30s or so. When I restore my internet connection then the cell comes online and Holochain correctly reports it as running.

I know this won't happen with tx2 but when I last worked on this we didn't need it working with tx2. It also wouldn't work with tx5 but no bootstrap server. So I wonder if the situation now is dealing with other configurations than this was made to work for.

There is currently no recovery mechanism for cells that get paused. But equally we have no online/offline status for Holochain. There is a start made [here](https://github.com/holochain/tx5/tree/main/crates/tx5-online) but it's not ready for use.

I'm also curious what got logged with `CellNetworkNotReady(PendingJoin(Failed))` for @matthme because there should have been an error logged when that cell failed to join the network which would tell me why that wasn't retryable. It would also be useful to know what configuration people are expecting this to work with. I don't think this is difficult to polish off but because it's difficult to automate the tests I do need to know what scenarios I'm trying to cover

**Comment by ThetaSinner** [comment] 2023-12-07 15:10
I'll clarify the requirement I've built in as a temporary solution here. If bootstrapping will be part of your network join for the cell, then you must be able to reach *a* boostrap server. That does not have to be the Holo bootstrap server. It could be on a local network or even the same machine. That will work fine.

Giving Holochain a concept of 'online'/'offline' is more complicated. Given it's a P2P system it is reasonable to me that the cell needs to go through the 'network join' even if that's just so that it can talk to other cells on the same conductor. I think the 'offline' behaviour is going to have to be quite subtle and prune out network calls when we know what isn't reachable.

If we don't mind lots of errors for the moment we could permit the network join even where there is no network available. That must means remote connections will fail and there will be no bootstrapping. Bootstrapping runs often enough now that it would  be a reasonable recovery mechanism when the internet connection is restored. It would be slower than it could be but it might be closer to the desirable behaviour

**Comment by maackle** [comment] 2023-12-18 20:31
The ideal solution to all of this is of course pub/sub. If everything happened in terms of pub/sub, all gets would be local and we would never wait for network calls. Of course that's not immediately helpful though.

Yes, the only other alternative is "detecting being offline" and pruning out network calls wherever they happen. I do wonder if that's any more simple than just implementing pub/sub though.

**Comment by samjoc** [comment] 2024-02-14 17:00
Hello, i'm not sure if this id the correct place to ask, but i has the problem with finding peers in VMbox'ed ubuntu with holochain launcher, it is idle in infinity search loop and can't find peers.
'''
[2024-02-14T15:25:21.788305317+01:00] INFO - request; msg=EnableApp { installed_app_id: "AppStore" }
[2024-02-14T15:25:22.584299994+01:00] INFO - request; msg=ListApps { status_filter: None }
[2024-02-14T15:25:22.584893959+01:00] ERROR - Failed to load icon src for app with id AppStore
[2024-02-14T15:25:22.589668728+01:00] INFO - Launched Holochain 0.2.3
[2024-02-14T15:25:22.589883330+01:00] INFO - request; msg=ListApps { status_filter: None }
[2024-02-14T15:25:22.590489357+01:00] ERROR - Failed to load icon src for app with id AppStore
[2024-02-14T15:25:22.599981026+01:00] INFO - request; msg=ListApps { status_filter: None }
[2024-02-14T15:25:22.600876095+01:00] ERROR - Failed to load icon src for app with id AppStore
[2024-02-14T15:25:22.618456531+01:00] INFO - request; msg=ListApps { status_filter: None }
[2024-02-14T15:25:22.619308389+01:00] ERROR - Failed to load icon src for app with id AppStore
[2024-02-14T15:25:22.713254334+01:00] INFO - Opening app AppStore
[2024-02-14T15:25:24.546082580+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:24.545969Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to ping without candidate pairs. Connection is not possible yet.

[2024-02-14T15:25:34.125378982+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:34.125212Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to accept RTP stream is already closed

[2024-02-14T15:25:34.126237643+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:34.125279Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to accept RTCP stream is already closed

[2024-02-14T15:25:34.126446505+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:34.125595Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to read from candidate udp4 relay 137.184.154.88:56885 related 0.0.0.0:47016: read udp 137.184.154.88:56885: use of closed network connection

[2024-02-14T15:25:34.126523219+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:34.125729Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to read from candidate udp4 relay 137.184.154.88:60763 related 10.0.2.15:50344: read udp 137.184.154.88:60763: use of closed network connection

[2024-02-14T15:25:34.126556692+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:25:34.125881Z[0m [33m WARN[0m [2mtx5_go_pion_sys[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.3-alpha/src/lib.rs[0m[2m:[0m[2m224:[0m Failed to read from candidate udp4 relay 137.184.154.88:49303 related 10.0.2.15:49730: read udp 137.184.154.88:49303: use of closed network connection

[2024-02-14T15:26:23.954683289+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:26:23.954522Z[0m [31mERROR[0m [2mkitsune_p2p::gossip::sharded_gossip[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kitsune_p2p-0.2.3/src/gossip/sharded_gossip.rs[0m[2m:[0m[2m563:[0m Tgt expired [36, 65, 235, 234, 169, 108, 89, 193, 229, 79, 192, 65, 250, 148, 113, 11, 241, 79, 58, 46, 155, 200, 219, 139, 200, 212, 135, 162, 196, 14, 184, 76]

[2024-02-14T15:26:23.954841656+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:26:23.954639Z[0m [31mERROR[0m [2mkitsune_p2p::gossip::sharded_gossip[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kitsune_p2p-0.2.3/src/gossip/sharded_gossip.rs[0m[2m:[0m[2m563:[0m Tgt expired [36, 65, 235, 234, 169, 108, 89, 193, 229, 79, 192, 65, 250, 148, 113, 11, 241, 79, 58, 46, 155, 200, 219, 139, 200, 212, 135, 162, 196, 14, 184, 76]

[2024-02-14T15:26:23.954874718+01:00] INFO - [HOLOCHAIN 0.2.3] [2m2024-02-14T14:26:23.954511Z[0m [31mERROR[0m [2mkitsune_p2p::gossip::sharded_gossip[0m[2m:[0m [2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kitsune_p2p-0.2.3/src/gossip/sharded_gossip.rs[0m[2m:[0m[2m563:[0m Tgt expired [36, 65, 235, 234, 169, 108, 89, 193, 229, 79, 192, 65, 250, 148, 113, 11, 241, 79, 58, 46, 155, 200, 219, 139, 200, 212, 135, 162, 196, 14, 184, 76]
'''

**Comment by pdaoust** [comment] 2024-03-01 17:05
@maackle 

> If everything happened in terms of pub/sub, all gets would be local and we would never wait for network calls.

I had no idea that pub/sub was meant to help with this, and now I think I need to revise my understanding of the use cases. Is there a design doc/discussion that I can follow? Is this less about something intrinsic to pub/sub and more about one particular pattern your app might implement (e.g,. subscribe to new links on a base, fetch the link targets in the subscription callback so your cache is warm)?

**Comment by maackle** [comment] 2024-03-01 22:16
@pdaoust it's simply that, in pub/sub, there *are* no network calls (other than the act of subscribing), and that's why we would never have to wait for one.

One of the most crucial reasons why detecting "onlineness" is so important for UX is because we need to know if we can expect to be able to make network calls, and have the responses come back in a timely fashion, or at all. In pub/sub, those network calls are replaced by local queries which are more or less immediate.

More context: Pub/sub is a fundamental reversal in paradigm from push to pull. Holochain is currently in a pull model, which is fundamentally about blocking and polling, where the UI makes a query and then has to wait for the response in order to complete that query. Pub/sub allows for a push model, which is fundamentally reactive, where the UI is purely reacting to incoming publishes which could happen at any time, unexpectedly. The "query" part then is entirely local, and immediate, based on the information currently accumulated by all means, including pub/sub publishes. Pull models combine information retrieval and the querying of that information into a single operation -- push models treat those actions distinctly.

If this isn't immediately convincing then maybe we can collab on a design doc about this.

**Comment by pdaoust** [comment] 2024-03-04 19:27
@maackle okay, I think I get this -- pub/sub necessitates a shift in thinking/design from "getting stuff from the DHT" to "thinking about what information is important to people (and preloading their cache with that stuff using reactive)". There are parts that I don't understand, and yeah, I'd be down for working on a design doc, but... perhaps not quite yet :)

**Comment by abe-njama** [comment] 2024-07-22 15:50
Convert this to an integration test where we start off with SBD off then switch on to see whether Gossip works

**Closed** 2024-08-08 16:39 UTC
Labels: permanent, HOLO LAUNCH

**Comment by matthme** [comment] 2024-08-12 12:53
:tada:
