### ISSUE TITLE
[BUG] "Too much memory used (42Gb)" after a day of the conductor running

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3027] opened 2023-11-13 10:40 UTC
**Describe the bug**

I booted up [gather](https://github.com/darksoil-studio/gather/releases/tag/v0.0.4) (a tauri app packaging the conductor) as an always online node, and after a day, the OS complained that it was using too much memory, and reported holochain having used 42Gb of memory.

**Expected behavior**

I expect to be able to run always-online holochain nodes that don't crash after several days or weeks.

**System information:**
 - OS: [e.g. iOS] MacOS v13 Ventura
 - Holochain v0.2.3-rc.0
 
**Steps to reproduce**

1. Download [gather](https://github.com/darksoil-studio/gather/releases/tag/v0.0.4)
2. Run it
3. Wait a day

**Comment by ThetaSinner** [comment] 2023-11-13 11:59
Oh dear, if it's not CPU it's memory! I of course agree that Holochain should be able to run for longer periods of time. I have got a mini PC running just for the purpose of debugging these issues. They are difficult to trace back to a single cause but my hope is that each time we find *a* cause that's one fewer way it can go wrong :)

1. Do you still have nodes running so that if I try to reproduce this on my mini PC I'll have something to talk to that already has data?
2. Is gather available as a happ so I can run it headless? I can unpack the webhapp if not
3. Did you observe the behaviour at all? Did the memory jump up at some point or did it continuously grow? I should be able to reproduce this but it's useful to know we're seeing the same thing.

**Comment by guillemcordoba** [comment] 2023-11-13 12:18
1. Yes, I just rebooted my macmini node, the one that gave the error. The conductor booted fine and you should be able to talk to it with your own instances. 
2. Here you go: https://github.com/darksoil-studio/gather/releases/download/v0.0.4/gather.happ
3. I didn't observe the behavior no... But I did find strange that holochain was consuming like 100% of one of the cores for the first ~30 minutes of booting up the node, with almost no network activity.

**Comment by abe-njama** [comment] 2023-11-13 14:40
I ran Gather for approximately one hour and the application got to 35GB of memory.

<img width="419" alt="Screenshot 2023-11-13 at 17 39 53" src="https://github.com/holochain/holochain/assets/62102332/a934ee29-8a81-40cd-b0ba-ad788d08eb45">

**Comment by ThetaSinner** [comment] 2023-11-13 14:57
Great, I have my node running it with Holochain 0.2.3-rc.0. Just to be certain, the DNA hash I see when I list installed apps is `uhC0kdkl1h8BwUDwn4H8LirVnfB8-yDXWZhBBBO0s7Ei-aKrTkfta`?

I have performance stats recording with sysstats which I haven't used before but can hopefully give me some feedback without having to watch top.

**Comment by maackle** [comment] 2023-11-13 18:38
The init errors seem interesting. Perhaps there is something about the UI startup pattern that Holochain init can't handle. I would like to look at the actual zome functions being called. @guillemcordoba can you tell us which zome function(s) are being called when gather starts up for the first time? Or I can read the UI code, but asking is easier.

**Comment by guillemcordoba** [comment] 2023-11-13 19:00
This one is the only one that's executed at first: [`get_agent_profile`](https://github.com/holochain-open-dev/profiles/blob/d630d54692eb1f9b9939bdf3673c27978f6c0535/crates/coordinator/src/lib.rs#L131)

**Comment by ThetaSinner** [comment] 2023-12-07 16:23
Are we okay to close this issue and focus on #3028? I believe this is a consequence of the other issue. It'd be better if we didn't claim this much memory at once but for now I'd rather not impose limitations on Holochain's scaling just because it uses an unreasonable amount of memory when overloaded

**Comment by guillemcordoba** [comment] 2023-12-07 16:37
Yeah that makes sense... Let's see if we can fix this!

**Closed** 2023-12-11 12:33 UTC
